# Generated by Django 2.0 on 2018-06-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualResidency',
            fields=[
                ('ActualResidencyID', models.IntegerField(primary_key=True, serialize=False)),
                ('Student', models.IntegerField(default=0)),
                ('DateTime', models.DateTimeField()),
                ('TimeIn', models.TimeField()),
                ('TimeOut', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditTable_Inventory',
            fields=[
                ('AuditID', models.IntegerField(primary_key=True, serialize=False)),
                ('AuditAction', models.IntegerField(default=0)),
                ('ItemID', models.IntegerField(default=0)),
                ('DateTime', models.DateTimeField()),
                ('DateTimeReturned', models.DateTimeField(null=True)),
                ('Borrower', models.IntegerField(default=0)),
                ('Lender', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('GroupID', models.IntegerField(primary_key=True, serialize=False)),
                ('Adviser', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('InboxID', models.IntegerField(primary_key=True, serialize=False)),
                ('Message', models.CharField(default='', max_length=1000)),
                ('DateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('ItemID', models.IntegerField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=50)),
                ('Quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_AuditAction',
            fields=[
                ('AuditActionID', models.IntegerField(primary_key=True, serialize=False)),
                ('Action', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Laboratory',
            fields=[
                ('LabID', models.IntegerField(primary_key=True, serialize=False)),
                ('LaboratoryName', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Schedule',
            fields=[
                ('ScheduleID', models.IntegerField(primary_key=True, serialize=False)),
                ('Day', models.CharField(default='', max_length=20)),
                ('Time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Term',
            fields=[
                ('TermID', models.IntegerField(primary_key=True, serialize=False)),
                ('Term', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_UserStatus',
            fields=[
                ('UserStatusID', models.IntegerField(primary_key=True, serialize=False)),
                ('UserStatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_UserType',
            fields=[
                ('UserTypeID', models.IntegerField(primary_key=True, serialize=False)),
                ('UserType', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResidencyTimeSlot',
            fields=[
                ('ResidencyID', models.IntegerField(primary_key=True, serialize=False)),
                ('Term', models.IntegerField(default=0)),
                ('Laboratory', models.IntegerField(default=0)),
                ('Schedule', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResidencySchedule',
            fields=[
                ('StudentResSchedID', models.IntegerField(primary_key=True, serialize=False)),
                ('Group', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('NFCUniqueID', models.IntegerField(default=0)),
                ('UserType', models.IntegerField(default=0)),
                ('UserStatus', models.IntegerField(default=0)),
                ('Name', models.CharField(default='', max_length=50)),
                ('IDNumber', models.IntegerField(default=0)),
                ('PhoneNumber', models.IntegerField()),
                ('Email', models.CharField(default='', max_length=50)),
                ('Group', models.IntegerField(default=0)),
            ],
        ),
    ]
